version: '3.8'
services:
  dev-db:
    image: postgres:13
    container_name: houseMarketDb
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: houseMarket